pipeline {
	agent any

        stages {
 
            stage ('test') {
                steps {
                  dir("build_java"){
                        echo "mvn clean compile test"
                  }
                   
                   
                }
            }

            stage ('Create docker image') {
                steps {
                 echo "creando docker"
                }

            }
        }
}
